# Learning Numpy

In [3]:
import numpy as np

### Get Numpy Version

In [5]:
print (np.__version__)

1.18.1


### Create Numpy Array from Python List

In [8]:
py_fibonacci_list = [0, 1, 1, 2, 3, 5, 8, 13, 21]

In [11]:
py_fibonacci_list

[0, 1, 1, 2, 3, 5, 8, 13, 21]

In [9]:
np_array = np.array(py_fibonacci_list)

In [10]:
np_array

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21])

In [12]:
np_array * 10

array([  0,  10,  10,  20,  30,  50,  80, 130, 210])

### Create Numpy Array intrinsic way

In [14]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
np.arange(7) + 1

array([1, 2, 3, 4, 5, 6, 7])

### Numpy Array Attributes